pipelines:
  branches:
    master:
    - step:
        services:
          - docker
        script:
          - export IMAGE_NAME=tanigroup/alpine-php:latest
          - docker build -t $IMAGE_NAME .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME
